### ISSUE TITLE
Does this library provide access to the raw stream?

### ISSUE THREAD

**Issue by daveyjones** [audiofetch/ios-audiofetch-sdk-public-library#2]
In our application (live captioning and translation), we would need access to the raw stream. Is this possible with this library?

**Comment by beachcitiessoftware** [comment]
https://github.com/audiofetch/ios-audiofetch-sdk-public-library/blob/master/include/AudioFetchSDK/AudioManager.h#L182

```
@property(readonly, null_unspecified) float* floatBuffer;
@property(readonly) UInt32 floatBufferSize;
```

The floatBuffer will have the raw samples, and floatBufferSize will tell you how many samples, however your app would need to process these samples.  There is no metadata associated with a stream.

Then you can post a: diagnosticModeToggledNotification (See Notifications.h), with a bool object of true/false.  This will toggle on/off a notification that you can listen for called, audioBufferUpdateNotification, which will notify you when the floatBuffer has been updated.

**Comment by daveyjones** [comment]
Awesome, thanks! This should get me going in the right direction.
